name: Apt
favicon: null
layout_spectrum: 0.3261
typography_spectrum: 0.6409760462120175
title: 'Apt Branding & Marketing'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#8a8a8a'
    - '#d2d2d2'
    - '#5a5a5a'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
